// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3jpMCCYIgyt39WytkskVByhns2E3e6io',
    appId: '1:888229681052:web:ab56bfe98d1f8e11f25a59',
    messagingSenderId: '888229681052',
    projectId: 'ahess-maps',
    authDomain: 'ahess-maps.firebaseapp.com',
    storageBucket: 'ahess-maps.firebasestorage.app',
    measurementId: 'G-1K9REVTXCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeKk9JZV_P7Z7_qS6cdZ9SdhMXhQyywPo',
    appId: '1:888229681052:android:ddad62a4cfb4e216f25a59',
    messagingSenderId: '888229681052',
    projectId: 'ahess-maps',
    storageBucket: 'ahess-maps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1WKRylWAmcsdcpTyfHEtNPgksVHsh_s4',
    appId: '1:888229681052:ios:c72c33b863225050f25a59',
    messagingSenderId: '888229681052',
    projectId: 'ahess-maps',
    storageBucket: 'ahess-maps.firebasestorage.app',
    iosBundleId: 'com.ahesmaps.ahesMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1WKRylWAmcsdcpTyfHEtNPgksVHsh_s4',
    appId: '1:888229681052:ios:c72c33b863225050f25a59',
    messagingSenderId: '888229681052',
    projectId: 'ahess-maps',
    storageBucket: 'ahess-maps.firebasestorage.app',
    iosBundleId: 'com.ahesmaps.ahesMaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3jpMCCYIgyt39WytkskVByhns2E3e6io',
    appId: '1:888229681052:web:5f2116b52329bd55f25a59',
    messagingSenderId: '888229681052',
    projectId: 'ahess-maps',
    authDomain: 'ahess-maps.firebaseapp.com',
    storageBucket: 'ahess-maps.firebasestorage.app',
    measurementId: 'G-2ZXW9DLCFK',
  );

}